### ISSUE TITLE
RPM and current value is always Zero

### ISSUE THREAD

**Issue by readysetawesome** [SolidGeek/VescUart#21]
I'm working with this library and discovered some inconsistency around reading these values.  I'm very confused.  I don't think it's a problem with the library but I'm desperate for help.

I was previously able to read RPM and current data, but now they are always Zero.  Interestingly, the voltage data is populated as it was before when I call getVescValues(). But current and RPM stuck at zero no matter what inputs I give the board. Same board, same hardware, same firmware (VESC 5.1), just on a different day getting different results. Its very strange.

**Comment by vicgwee** [comment]
Have you tried the debug print? To print the payload that the vesc sends
