### ISSUE TITLE
Replace HardwareSerial* with Stream* to use with Bluetooth

### ISSUE THREAD

**Issue by vasimv** [SolidGeek/VescUart#27]
Thanks for your efforts. I've used your library for displaying stuff on an ESP32 module with LCD screen connected to VESC through bluetooth. No issues, but had to replace all HardwareSerial* to Stream* as BluetoothSerial object has Stream type. As i understand, there is no real need for a real serial port, so would be good to replace this in the code.

**Comment by SolidGeek** [comment]
I agree, it was implemented some time ago! Thanks, for the request 👍
