### ISSUE TITLE
Software serial for setSerialPort()

### ISSUE THREAD

**Issue by ImraanMitha** [SolidGeek/VescUart#9]
you use a hardware serial object for your serial port that's used to communicate. Since the atmega238p only has 1 serial port required for debug would it be possible to tweak the source code to use a SoftwareSerial object so that people with basic Arduino boards could use this library

**Comment by SolidGeek** [comment]
Take a look at the development branch, it supports software serial ☺️

**Comment by ImraanMitha** [comment]
cant believe I didnt see that at first! thank you for the response
